name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. جلب ملفات المشروع
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. تثبيت Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. تثبيت الحزم
      - name: Install dependencies
        run: npm install

      # 4. تشغيل الاختبارات
      - name: Run tests
        run: npm test
